/*-------------------------------------------------------------------------------
    LONG RUNNING ACTIVE REQUESTS
-------------------------------------------------------------------------------

.PURPOSE

    Identify requests that are currently executing and consuming time,
    CPU, reads or writes.

.WHY THIS MATTERS

    This script helps identify performance problems occurring right now.

    It is one of the first scripts to execute during an active incident.

.KEY METRICS

    ElapsedSeconds

        Total execution time of the request.

    CPUSeconds

        CPU consumed by the request.

    LogicalReads

        Number of pages read from memory.

    Reads

        Physical reads performed.

    Writes

        Writes generated by the request.

    WaitType

        Current wait affecting the request.

    BlockingSessionId

        Session currently blocking the request.

.HEALTHY

    Requests complete quickly.

    Few active requests.

    Low wait times.

.WARNING

    Long running requests.

    High logical reads.

    High CPU consumption.

    Blocking sessions.

.POSSIBLE CAUSES

    Blocking.

    Missing indexes.

    Large scans.

    Memory grant waits.

    Storage bottlenecks.

.NEXT ACTIONS

    Review execution plans.

    Review Health CPU Toolkit.

    Review Health IO Toolkit.

    Review Health Blocking Toolkit.

.COMMON INVESTIGATION APPROACH

    Long Duration + Low CPU

        Usually waiting on a resource.

    Long Duration + High CPU

        Usually CPU intensive.

    Long Duration + High Reads

        Usually indexing or query design issues.

    Long Duration + Blocking Session

        Usually a concurrency issue.

-------------------------------------------------------------------------------*/

SELECT r.session_id
      ,r.status
      ,r.command
      ,DB_NAME(r.database_id) AS DatabaseName
      ,r.cpu_time / 1000.0 AS CPUSeconds
      ,r.total_elapsed_time / 1000.0 AS ElapsedSeconds
      ,r.logical_reads
      ,r.reads
      ,r.writes
      ,r.wait_type
      ,r.blocking_session_id
      ,t.text
FROM sys.dm_exec_requests r
CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) t
WHERE r.session_id > 50
ORDER BY r.total_elapsed_time DESC;
GO

/*-----------------------------------------------------------------------------
    HISTORICAL QUERY OUTLIERS
-----------------------------------------------------------------------------

.PURPOSE

    Identify queries that experienced unusually long executions.

.WHY THIS MATTERS

    A query may normally perform well but occasionally experience
    extremely poor execution times.

    This script helps identify those outliers.

.KEY METRICS

   MaxDurationMs

        Longest execution ever recorded in the plan cache.

    AvgDurationMs

        Avurage execution duration.

    ExecutionCount

        Number of executions recorded.

.HEALTHY

    MaxDuration remains relatively close to Average Duration.

.WARNING

    Extremely high MaxDuration values.

.POSSIBLE CAUSES

    Parameter sniffing.

    Blocking.

    Statistics changes.

    Memory pressure.

   Storage latency spikes.

    Plan regressions.

.HOW TO INTERPRET
    Example:

        ExecutionCouut = 10,000

        AvgDurationMs = 500

        MaxDurationMs = 300,000

    Interpretation:

        Query usually performs well but experienced
        at least one extremely poor execution.

    This is a strong indicator for:

        Parameter Sniffing

        Blocking incidents

        Resource contention

.NEXT ACTIONS

    Review Query Store.

    Review execution plans.

    Compare fast vs slow executions.

-------------------------------------------------------------------------------*/

SELECT TOP (25) qs.execution_count
      ,qs.total_elapsed_time / 1000 AS TotalDurationMs
      ,qs.max_elapsed_time / 1000 AS MaxDurationMs
      ,qs.total_elapsed_time / NULLIF(qs.execution_count,0) / 1000 AS AvgDurationMs
      ,st.text
FROM sys.dm_exec_query_stats qs
CROSS APPLY sys.dm_exec_sql_text(qs.sql_handle) st
ORDER BY qs.max_elapsed_time DESC;
GO

SELECT TOP (25) qs.execution_count
      ,qs.max_elapsed_time / 1000 AS MaxDurationMs
      ,qs.total_elapsed_time / NULLIF(qs.execution_count,0) / 1000 AS AvgDurationMs
      ,qs.total_worker_time / NULLIF(qs.execution_count,0) / 1000 AS AvgCPUms
      ,qs.total_logical_reads / NULLIF(qs.execution_count,0) AS AvgReads
      ,st.text
FROM sys.dm_exec_query_stats qs
CROSS APPLY sys.dm_exec_sql_text(qs.sql_handle) st
WHERE qs.execution_count > 5
ORDER BY AvgDurationMs DESC;